baseURL = "https://promhippie.github.io/scw_exporter/"
languageCode = "en-us"
title = "Scaleway Exporter"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "Thomas Boerger"
  description = "Export Scaleway metrics for Prometheus"
  keywords = "prometheus, exporter, scaleway, scw"
