baseURL = "https://promhippie.github.io/scw_exporter/"
languageCode = "en-us"
title = "Scaleway Exporter"
pygmentsUseClasses = true

[markup.goldmark.renderer]
  unsafe = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "Thomas Boerger"
  description = "Prometheus exporter for Scaleway"
  keywords = "prometheus, exporter, scaleway, scw"
